<?php
$title = 'Add new thriller';
$this->headTitle($title);
?>
  <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$book = $form->get('title');
$book->setAttribute('class', 'form-control');
$book->setAttribute('placeholder', 'Book title');

// This provides a default CSS class and placeholder text for the artist element:
$author = $form->get('author_id');
$author->setAttribute('class', 'form-control');

$isbn = $form->get('isbn');
$isbn->setAttribute('class', 'form-control');
$isbn->setAttribute('placeholder', 'Book ISBN');

$exc = $form->get('excitement_factor');
$exc->setAttribute('class', 'form-control');
$exc->setAttribute('placeholder', 'Excitement Factor');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('thriller', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
  <div class="form-group">
      <?= $this->formLabel($book) ?>
      <?= $this->formElement($book) ?>
      <?= $this->formElementErrors()->render($book, ['class' => 'help-block']) ?>
  </div>
  <div class="form-group">
      <?= $this->formLabel($author) ?>
      <?= $this->formElement($author) ?>
      <?= $this->formElementErrors()->render($author, ['class' => 'help-block']) ?>
  </div>
  <div class="form-group">
      <?= $this->formLabel($isbn) ?>
      <?= $this->formElement($isbn) ?>
      <?= $this->formElementErrors()->render($isbn, ['class' => 'help-block']) ?>
  </div>
  <div class="form-group">
      <?= $this->formLabel($exc) ?>
      <?= $this->formElement($exc) ?>
      <?= $this->formElementErrors()->render($exc, ['class' => 'help-block']) ?>
  </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('product_id'));
echo $this->formHidden($form->get('book_id'));
echo $this->form()->closeTag();