<?php
$title = 'Add new album';
$this->headTitle($title);
?>
  <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist_id');
$artist->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
  <div class="form-group">
      <?= $this->formLabel($album) ?>
      <?= $this->formElement($album) ?>
      <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
  </div>
  <div class="form-group">
      <?= $this->formLabel($artist) ?>
      <?= $this->formElement($artist) ?>
      <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
  </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('product_id'));
echo $this->form()->closeTag();